name: CI Build server (linux)

on:
  workflow_call:
  workflow_dispatch:

# If you will push images to GHCR, you need write; otherwise use read.
permissions:
  contents: read
  packages: read

jobs:
  build_server:
    name: Server (Linux)
    runs-on: ubuntu-24.04
    env:
      PROGRAM: server
      PLATFORM: linux
    steps:
      - name: Checkout
        shell: bash
        run: |
          ROOT=~/b
          ROOT_REPO="$ROOT/$PROGRAM"
          ROOT_DEP="$ROOT/dep"
          JOB_SLOTS=$(nproc --all)
          echo "ROOT_REPO=$ROOT_REPO" >> "$GITHUB_ENV"
          echo "ROOT_DEP=$ROOT_DEP" >> "$GITHUB_ENV"
          echo "JOB_SLOTS=$JOB_SLOTS" >> "$GITHUB_ENV"
          mkdir -p "$ROOT_REPO" && cd "$_" || exit 1
          git init .
          git config core.symlinks true
          git remote add origin ${{ github.event.pull_request.head.repo.clone_url || github.repositoryUrl }}
          git pull origin ${{ github.event.pull_request.head.ref || github.ref_name }} --depth=1 || true
          git submodule update --jobs=$JOB_SLOTS --init --depth=1 || true

      - name: Dependencies
        shell: bash
        run: |
          mkdir -p "$ROOT_DEP" && cd "$_" || exit 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # If you want to use GITHUB_TOKEN:
          password: ${{ secrets.GITHUB_TOKEN }}
          # Or, if you prefer a PAT stored as GHCR_PAT, use:
          # password: ${{ secrets.GHCR_PAT }}

      - name: Compile
        shell: bash
        run: |
          cd "$ROOT_REPO"
          BUILD_SCRIPT=".github/workflows/ci/build_linux.sh"
          PLATFORM=
          chmod +x "$BUILD_SCRIPT"
          $BUILD_SCRIPT "$ROOT_DEP" $JOB_SLOTS
