name: CI Build server (linux)

on:
  workflow_call:

permissions:
  packages: read

jobs:
  build_server:
    name: Server (Linux)
    runs-on: ubuntu-24.04
    env:
      PROGRAM: server
      PLATFORM: linux
    steps:
      - name: Checkout
        shell: bash
        run: |
          # Settings (linux-only)
          ROOT=~/b
          ROOT_REPO="$ROOT/$PROGRAM"
          ROOT_DEP="$ROOT/dep"
          JOB_SLOTS=$(nproc --all)

          # Share with other steps
          echo "ROOT_REPO=$ROOT_REPO" >> "$GITHUB_ENV"
          echo "ROOT_DEP=$ROOT_DEP" >> "$GITHUB_ENV"
          echo "JOB_SLOTS=$JOB_SLOTS" >> "$GITHUB_ENV"

          # Checkout repo
          mkdir -p "$ROOT_REPO" && cd "$_" || exit 1
          git init .
          git config core.symlinks true
          git remote add origin ${{ github.event.pull_request.head.repo.clone_url }}
          git pull origin ${{ github.event.pull_request.head.ref }} --depth=1
          git submodule update --jobs=$JOB_SLOTS --init --depth=1

      - name: Dependencies
        shell: bash
        run: |
          mkdir -p "$ROOT_DEP" && cd "$_" || exit 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        shell: bash
        run: |
          cd "$ROOT_REPO"

          # Use linux build script
          BUILD_SCRIPT=".github/workflows/ci/build_linux.sh"
          PLATFORM=   # clear to avoid interference

          chmod +x "$BUILD_SCRIPT"
          $BUILD_SCRIPT "$ROOT_DEP" $JOB_SLOTS
